# Generated by Django 4.2.10 on 2024-02-16 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('alias_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('transcription', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'word',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id_word', models.OneToOneField(db_column='id_word', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dictionary.word')),
            ],
            options={
                'db_table': 'word_group',
                'managed': False,
            },
        ),
    ]
