# Generated by Django 4.2.10 on 2024-02-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_group_word_delete_categories_wordgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'managed': False, 'verbose_name': 'Тематическая группа', 'verbose_name_plural': 'Тематические группы'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'managed': False, 'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
        migrations.AlterModelOptions(
            name='wordgroup',
            options={'managed': False, 'verbose_name': 'Связь между группами и словами', 'verbose_name_plural': 'Связи между группами и словами'},
        ),
    ]
