# Generated by Django 4.2.10 on 2024-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_group_options_alter_word_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'Список транскрипций',
                'verbose_name_plural': 'Список транскрипций',
                'db_table': 'transcription_list',
                'managed': False,
            },
        ),
    ]
