# Generated by Django 4.2.10 on 2024-05-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_cyrillic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptionlist',
            options={'managed': False, 'verbose_name': 'Элемент списка транскрипций', 'verbose_name_plural': 'Элементы списка транскрипций'},
        ),
    ]
