# Generated by Django 4.2.10 on 2024-08-11 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyrillic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cyrillic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название группы')),
                ('alias_name', models.CharField(max_length=128, unique=True, verbose_name='Кодовое обозначение для группы')),
                ('icon', models.ImageField(upload_to='group_icons', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тематическая группа',
                'verbose_name_plural': 'Тематические группы',
                'db_table': 'group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Слово')),
                ('alias_name', models.CharField(max_length=128, unique=True, verbose_name='Кодовое обозначение для слова')),
                ('transcription', models.CharField(blank=True, max_length=128, null=True, verbose_name='Транскрипция')),
                ('example', models.TextField(blank=True, null=True, verbose_name='Пример')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dictionary_images', verbose_name='Изображение')),
                ('audio', models.FileField(blank=True, null=True, upload_to='words_audio', verbose_name='Аудио')),
                ('stress', models.CharField(max_length=128, verbose_name='Ударение')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'db_table': 'word',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.group', verbose_name='Тематическая группа')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Связь между группами и словами',
                'verbose_name_plural': 'Связи между группами и словами',
                'db_table': 'word_group',
                'managed': True,
                'unique_together': {('word', 'group')},
            },
        ),
        migrations.CreateModel(
            name='WordDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
            options={
                'db_table': 'word_day',
                'managed': True,
                'unique_together': {('word', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TranscriptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dictionary.cyrillic', verbose_name='Буква')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Элемент списка транскрипций',
                'verbose_name_plural': 'Элементы списка транскрипций',
                'db_table': 'transcription_list',
                'managed': True,
                'unique_together': {('letter', 'word')},
            },
        ),
    ]
