# Generated by Django 4.2.10 on 2024-08-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordday',
            options={'managed': True, 'verbose_name': 'Слово дня', 'verbose_name_plural': 'Слова дня'},
        ),
        migrations.AlterField(
            model_name='wordday',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='wordday',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word', verbose_name='Слово дня'),
        ),
    ]
