# Generated by Django 4.2.10 on 2024-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название группы')),
                ('alias_name', models.CharField(max_length=128, unique=True, verbose_name='Кодовое обозначение для группы')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='group_icons', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тематическая группа',
                'verbose_name_plural': 'Тематические группы',
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'Список транскрипций',
                'verbose_name_plural': 'Список транскрипций',
                'db_table': 'transcription_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Слово')),
                ('alias_name', models.CharField(max_length=128, unique=True, verbose_name='Кодовое обозначение для слова')),
                ('transcription', models.CharField(blank=True, max_length=128, null=True, verbose_name='Транскрипция')),
                ('example', models.TextField(blank=True, null=True, verbose_name='Пример')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dictionary_images', verbose_name='Изображение')),
                ('audio', models.FileField(blank=True, null=True, upload_to='words_audio', verbose_name='Аудио')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'db_table': 'word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связь между группами и словами',
                'verbose_name_plural': 'Связи между группами и словами',
                'db_table': 'word_group',
                'managed': False,
            },
        ),
    ]
