# Generated by Django 4.2.10 on 2024-05-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wordday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordday',
            options={'managed': False, 'verbose_name': 'Слово дня', 'verbose_name_plural': 'Слова дня'},
        ),
    ]
