# Generated by Django 4.2.10 on 2024-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_transcriptionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyrillic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cyrillic',
                'managed': False,
            },
        ),
    ]
